---
title: "Titulo original corto pero claro"
subtitle: "EYP3007 - Consultoría Estadística"
format: 
  pdf: 
    include-in-header: 
      text: |
        \usepackage{amsmath}
    colorlinks: true
    geometry:
      - top=20mm
      - left=20mm
      - right=20mm
      - heightrounded
    fig-pos: H
    fontsize: 10pt
author: 
  - name: "Constanza Segovia González"
  - name: "Francisca Vilca Sánchez"
crossref:
  fig-title: Figura
  fig-prefix: figura
  tbl-title: Tabla
  tbl-prefix: tabla
tbl-cap-location: bottom
execute: 
  echo: false
  message: false
  warning: false
---

```{r}
library(rio)
library(dplyr)
library(ggplot2)
library(patchwork)

```

```{r}
datos <- import("ENS-reducida.xlsx")

datitos <- datos %>% 
  select(c(1:6),c(27:38),c(66:76))

```

## Introducción

aqui contamos en 4 parrafos como maximo q wea vamos a hacer

## Relación de las variables

### Trastorno del Sueño



### Estado Nutricional



## Conclusiones

algo debemos haber creado

## Bibliografía 

no se q wea poner de relleno aca pero debe estar en apa

LOS ANEXOOOOOS DEBERIAN IR AQUÍ